[package]
name = "one_note_xml_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
onenote_parser = { version = "0.3.0", default-features = false }
flate2 = "1.0.25"
base64 = "0.21.0"
sanitize-filename = "0.4.0"